// Arrays, Functions and objects
// Params-When declare/define
// placeholders, local variables
// Arguments--When Invoke/Call/Run
// Use Variables/Values, Multiple Params, Undefined

// function hello() {
//     console.log("hello Ron");
//     console.log("hello Emma");
//     console.log("hello Daniel");

// }

// hello();


// function hello() {
//     console.log("hello Ron");
//     console.log("hello Emma");
//     console.log("hello Daniel");
// }
// // By writing like this we can get all outputs.
// hello();

// function hello1() {
//     console.log("hello Ron");
// }

// function hello2() {
//     console.log("hello rajesh");
// }

// function hello3() {
//     console.log("hello siva");
// }

// //hello ron
// // WE WANT OUTPUT ONLY HELLO RON AS output we write like this
// hello1();

// //hello rajesh
// hello2();

// //hello siva
// hello3();

// // BY USING ONE FUNCTION WE CAN CALL NUMBER OF TIMES NOT TO WRITE EACH FUNCTION TO EVERY ONE
// function great(name){
//     console.log("Hello " + name);
//     // HERE we will give space between the invited commas "hello " COTES WE WILL GET SPACE BETWEEN NAMES
// }

// //great rajesh
// great("rajesh");
// great("thota");
// great("naidu");
// great("thota")
// great();

// variables
 const raj="raj"
 const thota="thota"
 const rak="rak"

 function great(name,study){
    console.log("Hello " + name+ " " +study);
 }

great(raj,"10th class");
great(thota,"+2 studying");
great(rak);





