//Switch
//Dice values: 1-6

//if

//else if

//Switch    


// Using if
// const dice = 5;

// if (dice === 1) {
//    console.log("You got one");
// }
// if (dice === 2) {
//    console.log("You got two");
// }
// if (dice === 3) {
//     console.log("You got three");
// }
// if (dice === 4) {
//    console.log("You got four");
// }
// if (dice === 5) {
//    console.log("You got five");
// }
// if (dice === 6) {
//    console.log("You got six");
// }
// if(dice >6 || dice <=0){
//     console.log("you did not roll the dice");
// }

//else if

// const dice = 5;

// if (dice === 1) {
//    console.log("You got one");
// }
// else if (dice === 2) {
//    console.log("You got two");
// }
// else if (dice === 3) {
//     console.log("You got three");
// }
// else if (dice === 4) {
//    console.log("You got four");
// }
// else if (dice === 5) {
//    console.log("You got five");
// }
// else if (dice === 6) {
//    console.log("You got six");
//    //here we no need to write conditions
// } else {
//     console.log("you did not roll the dice");
// }

//Switch

const dice = 1;
 switch (dice) {
 case 1:
 console.log("you got one");
 break;
   case 2:
console.log("you got two");
break;
  case 3: 
console.log("you got three");
break;
   case 4:
console.log("you got four");
break;
   case 5:
console.log("you got five");
break;
   case 6:
console.log("you got six");
break;
default:
    console.log("You did not roll the dice");
 }