// Conditional Statements
//  >, < , >==, <==, ==, ===, !=, !==
//else if and !!

// const num1=5;
// const num2=7;
// if (num1>num2)
// {
//     console.log("num 1 is greater");
// }
// else{
//     console.log("num 2 is greater");
// }

// Else if
// const num1=15;
// const num2=7;
// if (num1>num2)
// {
//     console.log("num 1 is greater");
// }
// //Here we apply elseif
// else if (num1>=num2){
//     console.log("both are equal");
// }
// else{
//     console.log("num 2 is greater");
// }

//
const num1=10;
const num2=25;
const value = false;
//by applying this ! mark the false became true and true became false
if (!value){
    console.log("Hey iam coming");
}