//Arrays,functions and Objects
//Functions -Declare,Invoke

function hello(){
    //logic
    console.log("Hello how are you ?");
    console.log("Hello are you there ?");
    console.log("Hey I'm Here! ?");
}
// suppose we want multiplie times of code we use this we don't want to write input multiple times Function hello(){}

hello();
//some code of 100 lines
hello();
//some codes of 100 lines
hello();
//some codes of 1000 lines

// console.log("Hello how are you ?");
// console.log("Hello are you there ?");
// console.log("Hey I'm Here! ?");

// // We want a code multiple times again we write whole code 


// console.log("Hello how are you ?");
// console.log("Hello are you there ?");
// console.log("Hey I'm Here! ?")

// But using FUNCTIONS WE DON'T WANT TO WRITE CODE MULTIPLIES TIMES